version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file cfn_template.yaml --s3-bucket test-codebuild-403 --output-template-file outputSamtemplate.yaml
artifacts:
  #type: zip
  files:
    - template.yaml
    - outputSamtemplate.yaml